on:
  push:
    branches:
      - main

jobs:
  main_job:
    name: Cool
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Do the sick action
      uses: ./